### ISSUE TITLE
Immediate crash in 1.15.2

### ISSUE THREAD

**Issue by lucsirotouka** [flier268/AutoHarvestMod#2]
[20:05:19] [main/INFO]: [CHAT] [自动收割]已切换到 收割 模式
[20:05:21] [main/INFO]: [CHAT] [自动收割]自动收割已启动
[20:05:21] [main/FATAL]: Unreported exception thrown!
java.lang.IllegalAccessError: tried to access field net.minecraft.class_1297.field_5987 from class com.flier268.autoharvest.TickListener
	at com.flier268.autoharvest.TickListener.harvestTick(TickListener.java:110) ~[AutoHarvest-1.0.1.jar:?]
	at com.flier268.autoharvest.TickListener.onTick(TickListener.java:66) ~[AutoHarvest-1.0.1.jar:?]
	at com.flier268.autoharvest.TickListener.lambda$new$0(TickListener.java:40) ~[AutoHarvest-1.0.1.jar:?]
	at net.fabricmc.fabric.api.event.client.ClientTickCallback.lambda$null$0(ClientTickCallback.java:33) ~[65933987-5218-4fcc-89c6-6c36fd69dbea.jar:?]
	at net.minecraft.class_310.handler$zcn000$tick(class_310.java:4047) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1514) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:964) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.8+build.186.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.8+build.186.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.8+build.186.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

It would be great if this mod could be updated to support 1.15.2.

**Comment by lucsirotouka** [comment]
Done.
Learnt something new.
