### ISSUE TITLE
[feature request] make compatible with quilt-loader 0.17.0

### ISSUE THREAD

**Issue by topia** [flier268/AutoHarvestMod#22]
In [curseforge](https://www.curseforge.com/minecraft/mc-mods/autoharvest/files), your mod file named with `[]`: `[1.18.1]AutoHarvest-1.3.2.jar`.
But the latest [quilt-loader](https://quiltmc.org/) (0.17.0) doesn't like the `[`/`]` characters in the filename and crashes.
If I renamed it to `1.18.1AutoHarvest-1.3.2.jar`, it would work as expected.

Could I ask you to name your mod file without `[`/`]`?

Thanks!

```
Caused by: org.quiltmc.loader.impl.entrypoint.QuiltEntrypointException: Exception while loading entries for entrypoint 'client' provided by 'autoharvest'
    at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:222)
    at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51)
    at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
    at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
    ... 21 more
Caused by: org.quiltmc.loader.impl.util.ExceptionUtil$WrappedException: java.net.URISyntaxException: Illegal character in path at index 69: file:/.../.minecraft/mods/[1.18.1]AutoHarvest-1.3.2.jar
    at org.quiltmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51)
    at org.quiltmc.loader.impl.util.UrlUtil.asPath(UrlUtil.java:67)
    at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.lambda$getMetadata$0(KnotClassDelegate.java:196)
    at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
    at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:190)
    at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:186)
    at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:153)
    at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:467)
    at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49)
    at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112)
    at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220)
    ... 24 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 69: file:/.../.minecraft/mods/[1.18.1]AutoHarvest-1.3.2.jar
    at java.base/java.net.URI$Parser.fail(URI.java:2974)
    at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
    at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3227)
    at java.base/java.net.URI$Parser.parse(URI.java:3175)
    at java.base/java.net.URI.<init>(URI.java:623)
    at java.base/java.net.URL.toURI(URL.java:1056)
    at org.quiltmc.loader.impl.util.UrlUtil.asPath(UrlUtil.java:65)
    ... 36 more
```

**Comment by flier268** [comment]
Ok
